[package]
name = "lsrs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
owo-colors = "4.2.3"
strum = "0.27.2"
strum_macros = "0.27.2"
tabled = { version = "0.20.0", features = ["derive"] }
